#ifndef CONFIGKSTATUSNOTIFIERITEM_H
#define CONFIGKSTATUSNOTIFIERITEM_H

#define HAVE_DBUSMENUQT 1
#define HAVE_DBUS 1

#define KSTATUSNOTIFIERITEM_ENABLE_DEPRECATED_SINCE(a, b) 0
#define KSTATUSNOTIFIERITEM_BUILD_DEPRECATED_SINCE(a, b) 0
#define KSTATUSNOTIFIERITEM_EXPORT

#endif // CONFIGKSTATUSNOTIFIERITEM_H
