.TH CKB-NEXT 1
.SH NAME
ckb-next \- Open source Corsair input device driver for linux and OSX
.SH SYNOPSIS
.B ckb-next
[\fBoptions\fR]
.SH DESCRIPTION
.B ckb-next
communicates with the ckb-next-daemon, using it to communicate with the Corsair
input device to drive animations, and map keybindings.
.SH OPTIONS
.TP
.BR \-v ", "\-\-version\fR
Displays version information.
.TP
.BR \-h ", "\-\-help\fR
Displays this help.
.TP
.BR \-b ", "\-\-background\fR
Starts in background, without display the main window.
.TP
.BR \-c ", " \-\-close\fR
Causes already running instance (if any) to exit.
