name: Bug Report
description: Report an issue with existing supported devices.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Due Diligence
        - Check if the device is supported [here.](/Supported_Hardware.md)
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: input
    id: name
    attributes:
      label: Device Name
      description: What is the name of the device you are using?
      placeholder: ex. K95 Platinum XT
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: OS Distro
      description: What Linux distro are you using?
      placeholder: ex. Arch
    validations:
      required: true
  - type: input
    id: install-choice
    attributes:
      label: Installation Method
      description: How did you install ckb-next?
      placeholder: ex. AUR
    validations:
      required: true
  - type: input
    id: build-version
    attributes:
      label: ckb-next version
      description: What version is found at the top of the Settings tab in the GUI.
      placeholder: ex. ckb-next 0.5.0
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect?
      description: What is the expected behavior? What is wrong or missing?
      placeholder: ex. The keyboard should work after system awakens from sleep.
    validations:
      required: true
  - type: textarea
    id: user-solutions
    attributes:
      label: Did you try anything that may have helped?
      description: Explain if you restarted your computer, logged out, replugged, etc. 
      placeholder: ex. The keyboard should work after system awakens from sleep.
    validations:
      required: false
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Is there anything else that may be helpful?
      value: |
        <details><summary>Report</summary>
        <p>

        Paste Here

        </p>
        </details>
    validations:
      required: false
  - type: textarea
    id: generated-report
    attributes:
      label: Generated Report
      description: In the ckb-next GUI, click the Generate Report button in the Settings tab of the user interface and attach the generated report to this issue or pase it here.
      value: |
        <details><summary>Report</summary>
        <p>

        Paste Here

        </p>
        </details>
    validations:
      required: false