name: Feature Request
description: Suggest an idea for this project.
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Due Diligence
        - Check if the device is supported [here.](/Supported_Hardware.md)
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: textarea
    id: enhancement-desc
    attributes:
      label: Enhancement Details
      description: What is it you want to see changed?
      placeholder: ex. Add a button to a place to do the thing.
    validations:
      required: true
  - type: input
    id: what
    attributes:
      label: What is it you want to see changed?
      description: (Can overlap with multiple things)
      placeholder: ex. "GUI" (or) K95 "Platinum XT"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: What does it do now?
      description: What does it do now if you want to change an existing feature?
      placeholder: ex. "No (or) "I want to suggest a new feature"
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: What does it do now?
      description: What does it do now if you want to change an existing feature?
      placeholder: ex. To change the brightness for the K95, you have a dropdown with four options.
    validations:
      required: true
  - type: textarea
    id: new-behavior
    attributes:
      label: What new thing should happen?
      description: Describe what you want to propose.
      placeholder: ex. Can we get a slider instead?
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Is there anything else that may be helpful?
      value: |
        <details><summary>Report</summary>
        <p>

        Type Here.

        </p>
        </details>
    validations:
      required: false