name: Feature Request
description: Suggest an idea for this project.
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Due Diligence
        - Check if the device is supported.
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: textarea
    id: enhancement-desc
    attributes:
      label: Enhancement Details
      description: What is it you want to see changed?
      placeholder: ex. Add a button to a place to do the thing.
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Is there anything else that may be helpful?
      value: |
        <details><summary>Report</summary>
        <p>

        Type Here.

        </p>
        </details>
    validations:
      required: false