name: I need help!
description: Request help.
title: " "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Please try these Resources first!
        * IRC chat: #ckb-next channel at [irc.libera.chat](https://web.libera.chat/?channels=#ckb-next)
        * [Matrix](https://matrix.to/#/#ckb-next:matrix.org): #ckb-next:matrix.org
  - type: markdown
    attributes:
      value: |
        ### Due Diligence
        - Check if the device is supported.
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: textarea
    id: question-subject
    attributes:
      label: Subject
      description: What do you need help with?
      placeholder: ex. Am I doing this right?
    validations:
      required: true
  - type: textarea
    id: question-body
    attributes:
      label: Can you elaborate?
      description: What do you need help with?
      placeholder: It's pretty self explanatory.
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Is there anything else that may be helpful?
      value: |
        Add any additional details here.
    validations:
      required: false
  - type: textarea
    id: generated-report
    attributes:
      label: Generated Report (if applicable)
      description: In the ckb-next GUI, click the Generate Report button in the Settings tab of the user interface and attach the generated report to this issue or pase it here.
      value: |
        Drag your generated report here if it's applicable.
    validations:
      required: false
      