name: New Device Request
description: Ask for the project to implement support for a new device.
title: "[New Device]: "
labels: ["new-device"]
body:
  - type: markdown
    attributes:
      value: |
        ### Due Diligence
        - Check if the device is supported [here.](/Supported_Hardware.md)
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: input
    id: device-model
    attributes:
      label: What is the name of the device?
      description: Please be specific. Copying the name from the sticker on the device or the title of Corsair's product page will yeild the best result.
      placeholder: ex. K95 PLATINUM XT
    validations:
      required: true
  - type: dropdown
    id: what-device
    attributes:
      label: What kind of device  is it?
      description: What kind of device would you like support for? Keep in mind that anything other than Mice and Keyboards are not currently being looked at for support in the immediate future. 
      options:
        - Keyboard
        - Mouse
        - Headphone
        - Mouse Pad
        - Lighting
        - Fan
        - Cases
        - Power Supplies
        - Control Modules (Commander PRO)
        - AIO Coolers
        - RAM
        - System
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to Corsair's Product Page
      description: Optionaly, please include a link to your exact device on Corsair's Website. 
    validations:
      required: false
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Is there anything else that may be helpful?
      value: |
        <details><summary>Report</summary>
        <p>

        Paste Here

        </p>
        </details>
    validations:
      required: false
  - type: textarea
    id: generated-report
    attributes:
      label: Generated Report
      description: In the ckb-next GUI, click the Generate Report button in the Settings tab of the user interface and attach the generated report to this issue or pase it here.
      value: |
        <details><summary>Report</summary>
        <p>

        Paste Here

        </p>
        </details>
    validations:
      required: false
      