name: New Device Request
description: Ask for the project to implement support for a new device.
title: "[New Device]: "
labels: ["new-device"]
body:
  - type: markdown
    attributes:
      value: |
        - Check if the device is supported [here.](/Supported_Hardware.md)
        - Search for similar bugs in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
        - Verify your installation is up-to-date.
        - One bug per issue.
  - type: textarea
    id: device-model
    attributes:
      label: What is the name of the device?
      description: Please be specific. Copying the name from the sticker on the device or the title of Corsair's product page will yeild the best result.
      placeholder: ex. K95 PLATINUM XT
    validations:
      required: true