---
inputs:
  packages:
    description: List of package(s) to install
    required: true

runs:
  using: composite
  steps:
    - name: Update package information
      run: apk update
      shell: bash --noprofile --norc -euxo pipefail {0}

    - name: Install package(s)
      run: apk add ${{ inputs.packages }}
      shell: bash --noprofile --norc -euxo pipefail {0}
