---
inputs:
  alpine-build-dependencies:
    default: >-
      make
      cmake
      eudev-dev
      pulseaudio-dev
      qt6-qtbase-dev
      qt6-qt5compat-dev
      qt6-qttools-dev
      quazip-dev
      xcb-util-wm-dev
      qt6-qtwayland-dev
      wayland-protocols

  archlinux-build-dependencies:
    default: >-
      base-devel
      cmake
      libsystemd
      zlib
      libpulse
      libxcb
      xcb-util-wm
      qt6-base
      quazip-qt6
      qt6-tools
      qt6-wayland
      wayland-protocols

  fedora-build-dependencies:
    default: >-
      cmake
      glibc
      libxcb-devel
      make
      pulseaudio-libs-devel
      qt6-linguist
      qt6-qttools-devel
      qt6-qtbase-devel
      quazip-qt6-devel
      qt6-qtwayland-devel
      systemd-devel
      xcb-util-devel
      xcb-util-wm-devel
      zlib-devel
      wayland-devel
      wayland-protocols-devel

  fedora-package-dependencies:
    default: >-
      rpm-build

  rhel-build-dependencies:
    default: >-
      cmake3
      dbusmenu-qt5-devel
      glibc
      libxcb-devel
      make
      pulseaudio-libs-devel
      qt5-linguist
      qt5-qtbase-devel
      qt5-qtx11extras-devel
      quazip-qt5-devel
      systemd-devel
      xcb-util-devel
      xcb-util-wm-devel
      zlib-devel

  rhel-package-dependencies:
    default: >-
      rpm-build

  ubuntu-qt5-build-dependencies:
    default: >-
      cmake
      libdbusmenu-qt5-dev
      libpulse-dev
      libqt5x11extras5-dev
      libquazip5-dev
      libudev-dev
      libxcb-ewmh-dev
      libxcb-screensaver0-dev
      libxcb1-dev
      qtbase5-dev
      qttools5-dev
      zlib1g-dev

  ubuntu-qt6-build-dependencies:
    default: >-
      build-essential
      cmake
      qt6-base-dev
      libudev-dev
      zlib1g-dev
      libpulse-dev
      libquazip1-qt6-dev
      qt6-tools-dev
      qt6-wayland
      qt6-wayland-dev
      libxcb-screensaver0-dev
      libxcb-ewmh-dev
      libxcb1-dev
      qt6-base-private-dev
      wayland-protocols

  ubuntu-package-dependencies:
    default: >-
      dpkg-dev
      file

runs:
  using: composite
  steps:
    - name: Install Dependencies (AlmaLinux/Amazon Linux/Rocky Linux)
      uses: ./.github/actions/dependencies/install/yum
      with:
        dependencies: epel-release
        packages: >-
          ${{ inputs.rhel-build-dependencies }}
          ${{ inputs.rhel-package-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'gcc gcc-c++' }}
      if: |
        startsWith(matrix.image, 'almalinux:') ||
        startsWith(matrix.image, 'amazonlinux:') ||
        startsWith(matrix.image, 'rockylinux:')

    - name: Install Dependencies (Arch Linux)
      uses: ./.github/actions/dependencies/install/pacman
      with:
        packages: >-
          ${{ inputs.archlinux-build-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'gcc' }}
      if: startsWith(matrix.image, 'archlinux:')

    - name: Install Dependencies (Fedora)
      uses: ./.github/actions/dependencies/install/yum
      with:
        packages: >-
          ${{ inputs.fedora-build-dependencies }}
          ${{ inputs.fedora-package-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'gcc gcc-c++' }}
      if: startsWith(matrix.image, 'fedora:')

    - name: Install Dependencies (Ubuntu / Debian Qt5)
      uses: ./.github/actions/dependencies/install/apt-get
      with:
        packages: >-
          ${{ inputs.ubuntu-qt5-build-dependencies }}
          ${{ inputs.ubuntu-package-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'g++ gcc' }}
      if: (startsWith(matrix.image, 'ubuntu:') || startsWith(matrix.image, 'debian:')) && (matrix.image == 'ubuntu:22.04' || matrix.image == 'debian:11')

    - name: Install Dependencies (Ubuntu / Debian Qt6)
      uses: ./.github/actions/dependencies/install/apt-get
      with:
        packages: >-
          ${{ inputs.ubuntu-qt6-build-dependencies }}
          ${{ inputs.ubuntu-package-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'g++ gcc' }}
      if: (startsWith(matrix.image, 'ubuntu:') || startsWith(matrix.image, 'debian:')) && matrix.image != 'ubuntu:22.04' && matrix.image != 'debian:11'

    - name: Install Dependencies (Alpine)
      uses: ./.github/actions/dependencies/install/apk
      with:
        packages: >-
          ${{ inputs.alpine-build-dependencies }}
          ${{ matrix.compiler == 'LLVM' && 'clang' || 'g++ gcc' }}
      if: startsWith(matrix.image, 'alpine:')
