if (APPLE)
    set(MACOSX_BUNDLE_NAME "ckb-next")
    set(CMAKE_INSTALL_PREFIX "/Applications")
    set(prefix "${MACOSX_BUNDLE_NAME}.app/Contents")
    set(INSTALL_RUNTIME_DIR "${prefix}/MacOS")
    set(INSTALL_CMAKE_DIR "${prefix}/Resources")
elseif (LINUX AND NOT LINUX_CUSTOM_INSTALL)
    set(CMAKE_INSTALL_PREFIX "/opt")
    set(prefix "ckb-next")
    set(INSTALL_RUNTIME_DIR "${prefix}")
    set(INSTALL_CMAKE_DIR "${prefix}")
endif ()

set(INSTALL_ANIMATIONS_DIR "${INSTALL_CMAKE_DIR}/ckb-animations")
