#!/bin/sh

start() {
    echo "Starting ckb"
    /usr/bin/ckb-daemon&
}

stop() {
    echo "Stopping ckb"
    killall ckb-daemon
}

# Logic.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status ckb-daemon
	;;
    restart|reload|condrestart)
	stop
	start
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac
